use super::*;

pub(super) fn register_billing_routes(router: Router) -> Router {
    router
        .route(
            "/admin/usage/records",
            get(billing::list_usage_records_handler),
        )
        .route("/admin/usage/summary", get(billing::usage_summary_handler))
        .route(
            "/admin/billing/events",
            get(billing::list_billing_events_handler),
        )
        .route(
            "/admin/billing/events/summary",
            get(billing::billing_events_summary_handler),
        )
        .route(
            "/admin/billing/ledger",
            get(billing::list_ledger_entries_handler),
        )
        .route(
            "/admin/billing/summary",
            get(billing::billing_summary_handler),
        )
        .route(
            "/admin/billing/accounts",
            get(billing::list_canonical_accounts_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/balance",
            get(billing::get_canonical_account_balance_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/benefit-lots",
            get(billing::list_canonical_account_benefit_lots_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/ledger",
            get(billing::list_canonical_account_ledger_handler),
        )
        .route(
            "/admin/billing/account-holds",
            get(billing::list_canonical_account_holds_handler),
        )
        .route(
            "/admin/billing/request-settlements",
            get(billing::list_canonical_request_settlements_handler),
        )
        .route(
            "/admin/billing/pricing-lifecycle/synchronize",
            post(pricing::synchronize_canonical_pricing_lifecycle_handler),
        )
        .route(
            "/admin/billing/pricing-plans",
            get(pricing::list_canonical_pricing_plans_handler)
                .post(pricing::create_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}",
            put(pricing::update_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/clone",
            post(pricing::clone_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/schedule",
            post(pricing::schedule_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/publish",
            post(pricing::publish_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/retire",
            post(pricing::retire_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-rates",
            get(pricing::list_canonical_pricing_rates_handler)
                .post(pricing::create_canonical_pricing_rate_handler),
        )
        .route(
            "/admin/billing/pricing-rates/{pricing_rate_id}",
            put(pricing::update_canonical_pricing_rate_handler),
        )
        .route(
            "/admin/billing/quota-policies",
            get(pricing::list_quota_policies_handler).post(pricing::create_quota_policy_handler),
        )
}
